# Generated by Django 4.2.4 on 2024-03-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
