# Generated by Django 4.2.4 on 2024-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_category_hotel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='category',
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ManyToManyField(to='hotels.category'),
        ),
    ]
