# Generated by Django 4.2.4 on 2024-03-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_category_hotel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price',
            new_name='room_price',
        ),
    ]
