# Generated by Django 4.2.4 on 2024-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_price_hotel_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='avilable_room',
            field=models.IntegerField(default=0),
        ),
    ]
