# Generated by Django 4.2.4 on 2024-03-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_image'),
        ('hotels', '0003_remove_hotel_category_hotel_category'),
        ('history', '0002_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
                ('cancel', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buying',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
