# Generated by Django 4.2.4 on 2024-03-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
