# Generated by Django 4.2.4 on 2024-03-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_delete_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancel',
        ),
    ]
